### ISSUE TITLE
Errore sconosciuto

### ISSUE THREAD

**Issue by rnhmjoj** [fazo96/asjon#22]
C'è quest'errore che continua a riempire il log. Non riesco a capire cos'è
```
[Tue Jun 23 2015 00:58:26 GMT+0200 (CEST)] ERROR TypeError: Cannot read property 'match' of undefined
  at TextMessage.match (/home/michele/Github/asjon/node_modules/hubot/src/message.coffee:29:10)
  at TextListener.matcher (/home/michele/Github/asjon/node_modules/hubot/src/listener.coffee:61:17)
  at TextListener.Listener.call (/home/michele/Github/asjon/node_modules/hubot/src/listener.coffee:39:17)
  at Robot.receive (/home/michele/Github/asjon/node_modules/hubot/src/robot.coffee:230:31)
  at Tg.Adapter.receive (/home/michele/Github/asjon/node_modules/hubot/src/adapter.coffee:66:12)
  at /home/michele/Github/asjon/node_modules/hubot-tg/src/tg.coffee:83:12
  at callbacks (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
  at param (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
  at next (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.multipart [as handle] (/home/michele/Github/asjon/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27)
  at next (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.urlencodedParser [as handle] (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:69:27)
  at next (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at /home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:107:5
  at IncomingMessage.onEnd (/home/michele/Github/asjon/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:199:16)
  at IncomingMessage.emit (events.js:104:17)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

```

**Comment by fazo96** [comment]
Segui lo stack trace? Finiti gli esami se no ci guardo io

**Comment by rnhmjoj** [comment]
Viene da uno degli script di hubot, non dal nostro codice.

**Comment by rnhmjoj** [comment]
Risolto. Nell'adapter di telegram i messaggi senza testo (tipo solo immagini, sticker) davano un `undefined`.
